[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "cc9a315beb0531adb7ad33a20de2e14ffd398f82"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "9430cc71d50f1d2a4d3a5a853fb95dbd1acfb04a9f0a5de9d7a9edc8f77af5c7"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "2b52614425cd48ec2f9e02a4ea903e16d545748a"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "ad52ba0762fbd43de3fecd5739b58c2fb5203306ceff2cffe039e56baafd1f0b"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-i686-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "aarch64"
git-tree-sha1 = "88b43bdf3ccdb9798bf3d29bef4b472091a73797"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "bbfaed24258a61e4c49d8739450821da0ea1b7c01542ce904c2e29550662d542"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1da889fbdc6d37311fa9e4e908c4f9eff66b9b73"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "da2495b9e4f3f4cfae564ab88e5cf83ee061b1472c7c164afda6a57d96b827ec"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind]]
arch = "powerpc64le"
git-tree-sha1 = "11e812fa126e5da69a35112e8df3f5c7fcf6e741"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "f5dbfaf1ed8a1cd4e3e7e14ca7c7d8d657c4372e41b581d04b301503a564bbf8"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "28e8f5ed325d68ee0be97be27bc7e1b5d14e1ca3"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "cbd4861fa7c9c187c15cfe690a7cbc5a38509c76885ca59b88182c1b3177b5c7"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "d72f37578725856710e5a06ead561c7f773e6214"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "7d0ed4c0c6d2a38eff16f960a171ef39a850b23ede2b5c5a596a0d058f217d08"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-i686-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "aarch64"
git-tree-sha1 = "41336c1727d49e2db4b9da44376fdff7908b856b"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "3644eb241b6bf4d751bfcff791906c3a2261ea96939010341d7b8ee763c93de9"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a5ae0e0d26727bcfe19f7005786f6d3a9de0a8d"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "f455c29e05c08807d926556ee2f87e0acb45d6a4f1ee323ef6edce93d6dc8cd1"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa746f71ec0e1cd84cdf0d4b80ec15ab3e0f3333"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "cfb51a7b88bede86830f7f58ce2112005db222ec1f20783397ca2afdb9320c6a"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "3460d9e72f39cce03a2d809dcc7dceacacb8c28b"
os = "windows"

    [[LLVMLibunwind.download]]
    sha256 = "c6524ed97abd557547d134ce846d58f6f99609f51bebc23c67a6f93b24892a19"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "87313a72ad9fe4ffe989c35528f5ecf128aabfeb"
os = "windows"

    [[LLVMLibunwind.download]]
    sha256 = "c2919c4043e5746b1d22a4c4a46fa5fc9bb5a3bddf7f943e65d3a138379bc7f3"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-v17.0.1-i686-w64-mingw32.tar.gz"

[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "0a2acfe55f2c8cd3c138f23ccca41c44b42ad938"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "b95f536a6ebb4e22f2c328b8edf3f8377d73e12fe7302bf768e5b944ff8d4fb2"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "47e6cce6c8380976f038052aacdc0a8687a54641"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "b77346094ace0534d2502d0ef73a5dc72d230133e21c02e05a63ba5b8be0a2fd"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-i686-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "aarch64"
git-tree-sha1 = "33d342263251a0135ca6037af891a85f7a882502"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "350e80dc51864dcc1dabc7a60df3dbca1d565a1d8bc664a0002cb8ed0e30db30"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a86f61e4b395b5f0db939894f36ab9202c5d708e"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "e7e14992723af4192a0ddf415c3ca41a0c087883aeb7aad4995e0e59b2567095"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "4dcd28fdf457dfe67d369ba8cbde7664a2b0fd93"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "3cee933cce5bd609d3122e94a62d94d695ecfdfa3059c6756842391fbb82be88"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "bc3cb1e177682d62da86e4c34a6e01c07740818f"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "de35fe7b52ad9f3e6d36094f689d017b1fc40f2655fe51387c1ac41bb376d19c"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "caa5f6d8642b2e63eb05fa845d97750244c6695d"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "4885a00622028a02dbf1f9d4afd58ed6c50ec12055bfc9dbe23f43dd6266c5df"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-i686-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "aarch64"
git-tree-sha1 = "5a2597f46b85f12bfa87bd4c46e8e01a1bad6105"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "88d6d91d2ad76b0355f757ad6b263a8baee40f38742c2b416ef7982554f6013e"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "704b8322f81ae9e61ed5a0152c7c7cba57f30e2b"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "42ea18bcbac9384d023bb99e426ca950a91a2838ca027dba81649554db05fcd3"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e548b8db17bd02eb985382a35104dda2c3339509"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "9b25aaf2e4fcd828dcd94469b09628b8e468135a522738b612f9ed77208d9081"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "9e5308edda12f1bd1312124eacb95edc87ee6286"
lazy = true
os = "windows"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "7d406a12edd59f35530b00ad6f65c559378894ed3e19090a82bdd2d3dc4979af"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "f59fe910c30de72bdd7a8b3027c6c6211feba31b"
lazy = true
os = "windows"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "9bea3d9c75fa21e9711f435b9ea6e059228edc648d593e1f07c517a0e9d6bb73"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-build_log-v17.0.1-i686-w64-mingw32.tar.gz"

[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "0159655a5d1bd707bc67bbc876eb778ba98a2c8b"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "c6669652640e8c39ca2a62436659daeab861c738590054d2ade3832f05f4e9f1"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "35229234560488ff8fdda0058fa9bc867d437c6c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "0bba9402b39e16ab443860dc3cb9eaf52dfe0c4ceb883bf782e854fe117213c3"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-i686-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "aarch64"
git-tree-sha1 = "69890b73a11497e7023406037fd8fc1ba395ba0b"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "74ee0b56d5b27011b6ca7caac4a2a8133e3c7bf2518750dbba8b13e0efe1f2ac"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6718a0745fb3bf76b9e1f27ca0e4ef79d07daef4"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "f36457311a35c05d92c0f10855f28b3cbb63ab325fd65494af03be4f874e5e33"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "eaafebbedefa79cf810c2cda417aa9779ab67bb9"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "65bfafd3b8e497bf713c4ad0182a962ae5c7cb8ade61c547a66700d9c29eb3cd"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b398aa72646f3fa6355ba66dec40bb3c7b68ae6e"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "7754ebb1e7658816334a7065833a7235de9e08092bb05beb10dc723c36e11969"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "77a6549bc2caa619d510b23f21ea0a7d09272fb6"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "791d41d7bdfd861fb82dc218fe11f15fbf5665d218562be8a1fefd71d9bae8be"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-i686-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "aarch64"
git-tree-sha1 = "27f34f34afd45976f3193ac23bee5999fa1e27ef"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "b4301d07c97ae546227c4e352d6151fd9d49428e79004989ab65a36cb291a95e"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "447125bdca3c3eecfcff75bbde97998645ad4f4c"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "2cc52acf1707eaef93e7a33dfd9442e0ef5f7393502204503e35cca6b732e3fa"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b839583f3128cfdbf0e6fc6c9c4bb6081015778e"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "3e9321a0c58fd08dd55e12cdfc430805ae9a3379221972ce224b2f3457070f61"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b1e6b16bc806e3a4b000955f0bde21ae5fd56a46"
lazy = true
os = "windows"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "510d67ee4afe87df6701811c1bb2a18bdfb64afaccf2c93f38907dfa49b026af"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "bb07416ed1f1fadc884207b337382d2dec731920"
lazy = true
os = "windows"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "2683a0e28bd4b9acc2b846ce4873d283b2bac5309e4d4f3fe76d210fc7ad40b8"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.1-GCC/LLVMLibunwind-extract_log-v17.0.1-i686-w64-mingw32.tar.gz"
