[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "594aeb6a4d0193a0871c74c6901852ce84df2d0f"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "36028f1ba1038b3546dabd47f74350d9e0b8c8878431fb6c035e4a0e26590ac4"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "ad968a5cc2cc9f690d7d88a0aa90a7ec104e5648"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "81ef739be107edbf6c06acafccaa4a4d32043ce04545e2f2474f925814c4076c"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "aarch64"
git-tree-sha1 = "a51156c07bfba58ca45deaf8965297c67604de09"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "43a8458223562d8ab3f6562b62db4d34b2f2f486ec5ed9e903b8a85afb7997ea"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fbf580c07af7e45031d475ac3001e244872cbb9b"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "8bfe0be6d5c7fc0f7c3aad9f9649fb455eb52c18d18c66bdd03c4db85a7fbd8e"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind]]
arch = "powerpc64le"
git-tree-sha1 = "6d8a73370a57f7926de7df191059b90303268df3"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "63ab725a8f7cc59ed4f6da8f2b12a3a3827065e65bd4eaa4d3819b84f8596fab"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "6403a9a11cf88fd73f0b6be30d9a1a6af088da3e"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "940e60e52c28af9bf5ec7225ee689a7c70ac47c9db12c9fe5d57eef9c1bef55f"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "acde88a77e45728d5f5acfb0936edaf7c0b4a94d"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "77154ac8e9563ec8ed0277e742d167ab829c30ee5d8c1a54e981b0516cc7ba41"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "aarch64"
git-tree-sha1 = "ba1244a9400fc7d7a91cdd146bb585ba2272ae04"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "0b5bb584486645331502387eac9a404c83c0ce4bbc5f961110ed18523cc68bd3"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "522f9aaff4e61f243a2e97526fdb68ca728b72c6"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "eb5dcd491f42050d62241d45c543075011c81fc26637d041b59e9a87e8d0082a"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48dd4f135684c16e3f6119c23a3765f006752b76"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "c614c53c3a442d6a678c16dbc3380bc03aad59aca6fd8e5833ae79c9ed648f6b"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "b1fcd6f5d849e79a0303cf663c4a93c473bdfd86"
os = "windows"

    [[LLVMLibunwind.download]]
    sha256 = "0ee59127677cb644850668e523ad690006568b1242c7a4ea9603fbd72f05b8d9"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "f7fc469f5b1eed902b116c45631e78dd51f7a0bd"
os = "windows"

    [[LLVMLibunwind.download]]
    sha256 = "405fcbb2245459c06d2d6f192c8ac74ff5be602196195c8cad20673ccb35fe51"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-i686-w64-mingw32.tar.gz"
[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "1f9854c3a2099e15636f0c3e7447cd051a4f9102"
os = "macos"
os_version = "17"

    [[LLVMLibunwind.download]]
    sha256 = "63f69a99bd43f1c7ae8d975c1c8705e2c18e6685181250b42cef722b9fd6d4e9"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-x86_64-apple-darwin17.tar.gz"
[[LLVMLibunwind]]
arch = "aarch64"
git-tree-sha1 = "c3a0c5befb718beb97750dcda1f0ed4d06e0f577"
os = "macos"
os_version = "20"

    [[LLVMLibunwind.download]]
    sha256 = "67df31b1d73d5095393d6174c7a3cd15ae380e08f8b66d77e3fa25e23e016609"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-aarch64-apple-darwin20.tar.gz"

[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "2648b77e49262748fccc99b827c44e5cc317e9b2"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "aedd84e749fe143da078ebd9234752a620a8afbd22661f08982521299bd38401"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "44d02dd7d13b0b52185d2f4990e4e32c55107edf"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "4b8d83d54029f08e473bc69435a093db74d041567fa905557dfaf280edc8e4b2"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "aarch64"
git-tree-sha1 = "bd63537a5437b0d0a9794c40179e46e7263e82d4"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "e719ce7be00ccb3c24765a028bcce37130f65da94cc243c6342d1438fdb21783"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fcb4e11bda57d153001c50503d2f69499f4a4df4"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "80a5998a21af813ca58971b11da4cdac1aaa7cab45daea5b1807241849c25007"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "3e344f3d888c4dce5d56c6d3dc2c9bec1eecc5ed"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "cd1809bdd2734077ddc8890835bc531ba857e4e43024c5c81e44c80e36cddf65"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "15b4d0aac79ba002da12efc5e28bf113c175dd61"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "e695549c3e6406b535377d65df0b1e0dffb45c695e22f8e9ddf2ee2d7692af7f"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "109e3a396357c04faf14b38795d534bae26894f4"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "92b5751f445380052600da67d37636fd0efc7abf71366d92a709d4b53df7598f"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "aarch64"
git-tree-sha1 = "41298136342a37198bfed32f897145233233f936"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "fabeefc92705ae3daaf208a1d84666f72273fb2b55e6ab25d1907c394a410a1d"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a9aa262b8b96b80190035a6fb975ead9d742c54"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "87eb2f053be298096eeac71dc942eb23c60554eba833191a795838a7e044e4eb"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "503dc2f0ec28856d2df512bedf165bb7c0be43de"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "f7bbaea98e096fccd6d6f784c8a05e837856fb4755f003ee629f581067bfd2fb"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "a5b17bf18d705af1b97dda57b974d7c04edab524"
lazy = true
os = "windows"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "367b1d84a0568828f419cdd0cb6246fef0525cce3a8cd262a19f8a209a0b99f5"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "210022aa1b58395a7ceefa76c3fbbc42433ebb50"
lazy = true
os = "windows"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "c3fa10ece743dd36c403063fc2ccab50b1885f2618d540ef11ba236d826ee872"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-i686-w64-mingw32.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "b14583ee83d9a30cba85a94b152cb137f72d438a"
lazy = true
os = "macos"
os_version = "17"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "cc3d999ab10c8b2dd5c20319acc8f9deb121d636a27548f4a695c2c1726e0b3b"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-x86_64-apple-darwin17.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "aarch64"
git-tree-sha1 = "3dd5f1394b72988266a1a72ddb1e027f12481d32"
lazy = true
os = "macos"
os_version = "20"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "0e540d103e78bbb86c72964d69b109627f0f388950d07a7155f55e2ef28b0462"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-aarch64-apple-darwin20.tar.gz"

[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e01e0027ee79043c09b55fd8e3345c6d9317569e"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "3541e882dee59e0e91a9c5bc5f8ebdfc9f1b2a0ec346f2e7b1645946ca11fca4"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "21d15bd3b2b609679e11cf233a95bf76b9170fe7"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "1ad093051bf06e4999473f756e5e1549bab1cebcfca3b1d387c61396a2a3e164"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "aarch64"
git-tree-sha1 = "34ee7a0ec56c71ca0a34d699a24d2ad976fd6902"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "0d86fbd220ec9f8300ba7a09c0137fffaecb9f4734e59cfc2f64b278ab6d2aaf"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abbb0283a89310c9993d2454ce6730f29064bc94"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "eb72e5a68744f923e2ee347ae9995656f9f95d9b675014ec54a5e6cef713481e"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "1aa5074f4c36d57303a668fea485498a70f3c0b0"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "210129b720d4c1dafcd46fb9464829b1dcb5b120e2e08dee1be1eeca11bd182b"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9dc4afca9de3515100e43e8a09a3877f2de32273"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "48ea6f216474f3e6c43b139c2997384ac7877a5d5dfec8533f5498e8c5a29a29"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "1c1b9964b9ad0add270c1734e8d6f9601edab3ad"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "2256074077f2bbcd6d10f02ebe1a23362bd3add8ac39403ff487f84896706a64"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "aarch64"
git-tree-sha1 = "d22d7cbe74f5c981829d5b453313c3dbdd67e887"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "9fe47ea8c9972773198e33b4634480db9b398a8828460cd37d9e06c02504bbb5"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97e31519647a6a3d7f1b8480badccc7b14a36174"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "35a97bc9ec0b31f75993e7ccd8d35d74913d364f9e2a66e189ddc0d2b127fbd1"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75fd4e27399e3e76d7b721a6d6b468d1c6188f2b"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "e689188a6f0908623565e47c311c546f05045402cd666bea3671fc73ac0c4da3"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4a29b1886b4c714ad02658857faf711022974338"
lazy = true
os = "windows"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "4f702f89a4dbe646c447f927cbbf0d47caad8cc8de0e45bfc610e692a02a61ba"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "041ed9d5970b3e9791ec8bee8f4e036decbbc26c"
lazy = true
os = "windows"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "27c5a26f9afd0e9d401eeee7ee28b4c4afd6e486abab6b8ed02f8a3b856588b6"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-i686-w64-mingw32.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5e4ded68671cbab5bc0a761c6d581bac9fc221c4"
lazy = true
os = "macos"
os_version = "17"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "9b75f0107913af1942306692339a018503929e4b4d7cf97d9f9b146f854d2bfa"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-x86_64-apple-darwin17.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "aarch64"
git-tree-sha1 = "eba076d276bb6676c17180b5897aa442afadffcc"
lazy = true
os = "macos"
os_version = "20"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "dd929ef5543770a32ac9729dbde491467153cb668619fb8b238e840150d5ced3"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-aarch64-apple-darwin20.tar.gz"
