[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "867f2d3b9e2934bcb3e4efdc2dc325113720a61c"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "b3fcb150be23fb0d341865165700fdeef5cce6dc6c12f0691da36c724467af60"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "3b6666aa69e8801a5300a1770d5fef13aea14151"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "c62d05fc13f1043eae5fa15a8fa18fb61cb35029dde590b02c7eb3f7140c748f"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "aarch64"
git-tree-sha1 = "fb92edaa9d44f38755f4469a44b3eabe6ec9ecca"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "b649820d3ccc4a3101b54e939d3bedd28554b3c2ac0ad7bcbf7437acd8687192"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad3362f4607bcb1fbaf4c130e3873b985f079905"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "ea73e879a33fdbead98eff9797c9bc28f7cff3eb8486824f8796148fe6543803"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind]]
arch = "powerpc64le"
git-tree-sha1 = "21f613d6c181a60cc6a6fc2b67a288531dcc42b6"
libc = "glibc"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "91c0a1fa57e43c6e91650f02fcb0cbe4477b13b47202405da816cfc1ec2d92e9"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "851b4d63cfa7d75acb4c45156d858d4076bc2c01"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "45d4f2f152e69267eba018f5d488ed64109465e92bc7eecc6b9d9021f0d0e963"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "a7aff4c4e103dec360051b9bccf36b1e91dd7993"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "83cd4a2d8927c386e84d055f7b5f7401f3610300935e6a2308a699fd1a444b4e"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "aarch64"
git-tree-sha1 = "234de635d9710456f844167c99e87280c2b9d721"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "c232d748d590ba3d1df25bbe470532c37942b04493974099ebd6b5ed339a5eb2"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "099ab948eeabe685606ccc0f26d9f17c6969a209"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "3c110db4876c1446484bf60d12e911b8765bbb38cb2b0ba598519bae18985c66"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cec3c4ec6bd867c175e6f991e5db86153f042d2f"
libc = "musl"
os = "linux"

    [[LLVMLibunwind.download]]
    sha256 = "522880ab354f209fa506c90ca93f25b076caae4057dc600417ab28d08ae5ad05"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind]]
arch = "x86_64"
git-tree-sha1 = "3460d9e72f39cce03a2d809dcc7dceacacb8c28b"
os = "windows"

    [[LLVMLibunwind.download]]
    sha256 = "7cc848a2f87c4c0950298767a2fb03a9457baf4e4dde3b399060108a8bfd6d7e"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind]]
arch = "i686"
git-tree-sha1 = "87313a72ad9fe4ffe989c35528f5ecf128aabfeb"
os = "windows"

    [[LLVMLibunwind.download]]
    sha256 = "ac77d13106a470f99413efb057ee6b9ef0a7cec147486475fb4079ab69b37525"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-v17.0.0-i686-w64-mingw32.tar.gz"

[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "cca6bea9ab0e79929ddd055b2f6c803b24aac6b4"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "4e3b7a7bd40f3447ea52d3b5ea00b498e4efeb32ecbb7d586c84018f4ab26c02"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "5344822ecf9557ba8a6810dd084a370e7dfb675c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "49345961bfffe2ae534de7475e06dfc4e90e9039b5a3ef863a88a5e1f50e4ac1"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "aarch64"
git-tree-sha1 = "ecc88f8b9e58090a1323eb11ddd4a5028352139c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "a3c4aa388e6c42f0fd1b6c68726e4b0b7e2fe2b1999032eb9e0419298b068846"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f85ae7a6e5bf32b4aa963848e90d4d4012111ddf"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "8bb53e4290df4bce30d837fe87e1d8c8f16dcbca948f3a4effea0a9449234a73"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "4e0fe134c26a2d316c617f609264e21640265807"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "16a637182950f7410520ae037ffe2f14087a2e35d81972bf0246fcbc3c855045"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "a88188180679138360b8c32e1675705572b254f6"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "f101e8e9ee91beee935050f92fe205c8d12244d3d5517975a2a26532e8bea3c9"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "7def8f92ac736274f303c086fad6cfc63cb03175"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "710b6a97619298e0e09ff4ffd835ed48bec5e084faee2c341723776d33f8717d"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "aarch64"
git-tree-sha1 = "b60b358a26186d2f2010673a928e394c0c85eed9"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "4427310c5f038241fe60444f0aa9484f90b068f7bfb979c36d5d1edaf9c803f9"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6981f0abc5057d440d64833d77a36e9a0d1d7dae"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "e7b0e4f63d38633b4defb58fb8f79dfd2eaebc189ec0e9e031ba1232295c0666"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3c9b50aad3ccfc90e805e57601a3a45bc77229a6"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "92217698dd760cfde71d539390e3e876638451f9dad5bfaf133c41024f6a679a"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "x86_64"
git-tree-sha1 = "95fc48a2eefded832a5f65d5ddfcae54e6b9c9e4"
lazy = true
os = "windows"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "0d3e967f7717c1600f709b8104a38e02b205b2cd56f329d6922bde24efa31304"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind-build_log]]
arch = "i686"
git-tree-sha1 = "4c6b0b392f95d3d04a2d889777b2224d2889e6d0"
lazy = true
os = "windows"

    [[LLVMLibunwind-build_log.download]]
    sha256 = "46feb171eebeeead080b3cf0da10f2a3016610bfdc04d840f31e85a51eaf20a1"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-build_log-v17.0.0-i686-w64-mingw32.tar.gz"

[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "891a6744422cf67f164ad47723c94951393b8e94"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "ed3fb956ec45c4cf78080bacbf6b1184fabf4a0504be2483be84777b3aba6b78"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "8a336412d6a3ab7f1eba3536f3b7d8425f8a1c52"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "22293e5eb59857d892575de335a83f57da20be8928340a99ac51ce4343176e7d"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "aarch64"
git-tree-sha1 = "ff305ff3233551d4b52cfec575e510925926ec08"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "0fdab50c7bb70d2e1d9a4eae23441a8e024f675f112d1c093425de7e0dfa10f7"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07e47337e9f1f63ac9c162e72ea12d0359b4b5e8"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "2e37560614b5d401215d606a50403e643707df3b371a4443dfc76d4f80fd2696"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "397e0f481262466435aab57c4b62353354457b28"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "b20958828faaed3785e53ffd93225980266dcbfa3344c1cf569d9f709a91bf80"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a8c0877978f30263c5ad19892ff7d8b0e11be471"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "d877fd99b2a93d733aa24fb75516adc7e4e62d8e3fa89edd9a241276780bb58b"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "cdd4072b17c2a840117ab3574b3d58bd33549ed2"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "7e5abaab140fdbeec764b53217aefcc32bf81417022580f9400829c8b5d019e6"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "aarch64"
git-tree-sha1 = "729b2267c7bf948db4e7617ad47c736227d01e64"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "b8fbd8dcb768acbc94128a021fadb31c155b1c222a6d78c28261d3127d9bc136"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ed06df922a608f5e05babff968c6c98ff68bead"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "ae7bda52cb900e17cdbc92d214b0f58ae50a3c66d55344d769498c79bb0d746a"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "575bfde0739a556d17bce2e579747ed756048303"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "824e392bef3a10780d54d26eb5cca32573a2f356de2a28e2046bdd3c94c172f6"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "x86_64"
git-tree-sha1 = "85cdc816de6724608ae3879ee96df0537ac8427d"
lazy = true
os = "windows"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "cae1013f64f6c09cde4453e3ab063d6925a7107526c075d02476eb55e2df35ec"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibunwind-extract_log]]
arch = "i686"
git-tree-sha1 = "ddad3d2f558bd17bd4ddad85544b63278c9714e1"
lazy = true
os = "windows"

    [[LLVMLibunwind-extract_log.download]]
    sha256 = "2f8ae58279ef9bb8bdc85fdc78460efe9b599132012ff43bcab5e36a4e3e58a9"
    url = "https://github.com/staticfloat/LLVMLibunwind_jll.jl/releases/download/v17.0.0/LLVMLibunwind-extract_log-v17.0.0-i686-w64-mingw32.tar.gz"
